#!/usr/bin/python3 python
# encoding: utf-8
'''
@author: 孙昊
@contact: smartadpole@163.com
@file: transpose_reshape.py
@time: 2023/3/17 下午3:38
@desc: 
'''
import sys, os

CURRENT_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(CURRENT_DIR, '../../'))

import argparse
import numpy as np


def MyTRTR2(array, size):
    print(array.shape)
    # print(array)
    C, H, W = size
    output = np.zeros((C, H, W), dtype=int)
    for c in range(C):
        for h in range(H):
            for w in range(W):
                v = array[c][h][w]

                id = c * H * W + h * W + w
                c1 = id % C
                w1 = id // C % W
                h1 = id // (C * W)
                output[c1][h1][w1] = v

    return output


def MyTRTR(array, size):
    print(array.shape)
    # print(array)
    C, H, W = size
    output = np.zeros((C, H, W), dtype=int)
    for c in range(C):
        for i in range(H * W):
            v = array[c][i]

            id = c * H * W + i
            c1 = id % C
            w1 = id // C % W
            h1 = id // (C * W)
            output[c1][h1][w1] = v

    return output


def main():
    c, h, w = 5, 5, 8
    array = np.arange(1, c * h * w + 1)
    array_reshape = array.reshape((c, h, w))

    ret1 = array_reshape.reshape((h, w, c))
    ret1 = ret1.transpose(2, 0, 1)

    print(array_reshape)
    print("\nnumpy: \n", ret1.shape)
    print(ret1)

    ret2 = MyTRTR2(array_reshape, (c, h, w))
    print("\nlocal 3D: \n", ret2)


    array_reshape = array.reshape((c, h * w))
    ret3 = MyTRTR(array_reshape, (c, h, w))
    print("\nlocal 2D: \n", ret2)


if __name__ == '__main__':
    main()
